# Generated by Django 4.0 on 2021-12-30 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('my_board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='writer',
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
