# Generated by Django 4.0 on 2021-12-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_board', '0004_rename_reply_board_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board_reply',
            name='user',
            field=models.CharField(max_length=128),
        ),
    ]
